### ISSUE TITLE
Help With Flexparts?

### ISSUE THREAD

**Issue by jonnysp** [sttng/LDD#2]
Need you help with Flexparts?

**Comment by sttng** [comment]
I surely could use help with flex parts. Currently the whole code is quite messy. If you have some fix for flex parts feel free to clone and / or create a path. Also any other hint is surely welcome.

**Comment by jonnysp** [comment]
what I noticed is - in the geometry files (at the END) are the groups of points that are positioned with the LXFML matrix. Maybe this will help you.

You can take a look at my importer for c4d.
https://github.com/jonnysp/LDD2C4D/blob/src/LDD2C4D/LDD2C4Dv20.pyp#L193

jonny

**Comment by sttng** [comment]
Cool and thanks. Will surely have a look !

**Comment by jonnysp** [comment]
hi 
i have converted my converter as a comandline script

https://gist.github.com/jonnysp/15d3e4f4e641231a4649352b8ad4e020


PS: python3 pyldd2obj.py test01.lxf test

**Comment by sttng** [comment]
Thats nice !  I made some changes to make it run on python 2.7 (that old version is still the standard on macOS) and also added some UTF-8 compability.

https://github.com/sttng/LDD/blob/master/pyldd2obj.py

I just converted the UCS Falcon creating  an 500MB obj file and it works.

**Comment by jonnysp** [comment]
i hope the flex works to 👍

**Comment by sttng** [comment]
Yes flex works !

**Comment by jonnysp** [comment]
Fine! but i think the LOCReader is not working properly in py2

i have update my gist to works on py2 and py3

**Comment by sttng** [comment]
I tested your new version and it also works !
