### ISSUE TITLE
error

### ISSUE THREAD

**Issue by zhubenjie** [sttng/LDD#3]
DB Version: 2670
Database OK.
Scene "42083 Bugatti Chirion" Brickversion: 2670
Traceback (most recent call last):
  File "./lxftoobj.py", line 677, in <module>
    main()
  File "./lxftoobj.py", line 672, in main
    converter.Export(filename=obj_filename)
  File "./lxftoobj.py", line 578, in Export
    print(" (" + geo.designID + ") " + geo.Partname)
UnicodeEncodeError: 'gbk' codec can't encode character '\xd8' in position 27: illegal multibyte sequence

**Comment by sttng** [comment]
Which python file are you referring to (lxftoobj) ? Which OS ?

**Comment by zhubenjie** [comment]
LxfToObj.py

**Comment by zhubenjie** [comment]
linux 
```js
python ./pyldd2obj.py ./car.lxf ./qqq
```
```js
no LDD database found please install LEGO-Digital-Designer
```
