### ISSUE TITLE
pyldd2obj conversion error

### ISSUE THREAD

**Issue by ghost** [sttng/LDD#5]
I have an error when trying to convert a model to obj.
![image](https://user-images.githubusercontent.com/31226325/94747846-c7c9b580-0334-11eb-9388-c6f85615b75f.png)

**Comment by ghost** [comment]
the model
https://www.mybricks4u.com/uploads/6/7/8/0/6780867/4955_big_rig.lxf

**Comment by sttng** [comment]
Can you try https://github.com/sttng/LDD/blob/master/pylddlib.py This is a somehow improved version of pyldd2obj.

Also I saw your model has been saved with LDD 4.2 BrickSet version=604.1
I am using LDD 4.3.11 BrickSet version=2670 and the scripts have only been tested with that. I suggest to get LDD 4.3.11. Also be aware that Lego made a botched 4.3.12 available - this is a faulty update from Lego (and they never fixed it). Just get 4.3.11 :)

Nice model by the way. So I loaded it and saved it with LDD 4.3.11. Then I converted it with pylddlib.py and here is the result https://github.com/sttng/LDD/blob/master/assets/4955_big_rig.zip

Last but not least you may also have a look at https://github.com/sttng/LegoToR 
There is a tool that converts LDD lxf files into USD files, that may be an advantage over obj files.

**Comment by ghost** [comment]
Thank you for helping me.
I got LDD version 4.3.11 and resaved that model. Updated the script as well.
It says I use brick set version 777. Not sure how to update it at the moment.
But got the same problem.

Thanks, it's not my model but it's nice) Your exported model works perfectly.

But you're right, I need USD ideally, or smth with materials in it)
I think the error is somewhere in my setup, the script gives me this. I use python 3.8, but tested with 2.7 too.
![image](https://user-images.githubusercontent.com/31226325/94883335-426eff80-041f-11eb-901f-1631ba5ed748.png)
I found a software for a workaround, so this can be closed. But it would be nice to have a script too.

**Comment by sttng** [comment]
Hmmm ok.. Maybe some Windows vs macOS Python issues. I didn't test the script on Windows - might do in the future.

Anyway here an USD version: https://github.com/sttng/LDD/blob/master/assets/4955_big_rig_Scene_usda.zip

**Comment by sttng** [comment]
I pushed a new update of https://github.com/sttng/LegoToR I made some changes so it runs on Win 10 now (on my machine). Welcome any feedback.

**Comment by ghost** [comment]
Thank you for update.
The .usd model you did is amazing.
I tried the updated script and it works, although the output .usd is just 1kb in size.
I use RenderManProServer 23.4
Python 3.8.6

output is:
```bach
LegoToRHD Version 0.5.2
DB Version: 777
Database OK.
Scene "4955_big_rig_new" Brickversion: 777
Traceback (most recent call last):-----------------] 0.2%   (3023) PLATE 1X2
  File "C:\Users\Ilari\Downloads\LegoToR-master\LegoToR-master\LegoToRHD.py", line 711, in <module>
    main()
  File "C:\Users\Ilari\Downloads\LegoToR-master\LegoToR-master\LegoToRHD.py", line 698, in main
    converter.Export(filename=obj_filename)
  File "C:\Users\Ilari\Downloads\LegoToR-master\LegoToR-master\LegoToRHD.py", line 474, in Export
    lddmatri = self.allMaterials.getMaterialRibyId(materialCurrentPart)
AttributeError: 'Converter' object has no attribute 'allMaterials'
```

**Comment by sttng** [comment]
Are you sure you have all the other python files in the same directory ? 
Specifically:
- lego_colors.csv (needed for the colors)
- pylddlib.py (generic lego parts parsing functions)
- ParseCommandLine.py (well to parse command line)

**Comment by ghost** [comment]
I just copypaste the model to the folder with the master branch directory and call the script from there.

**Comment by sttng** [comment]
Could you send me the file which you saved again ? Thanks alot.

**Comment by ghost** [comment]
sure, it's the same file, resaved with ldd 4.3.11, just renamed.
[bigrig.zip](https://github.com/sttng/LDD/files/5322698/bigrig.zip)

**Comment by sttng** [comment]
For some odd reason your file works under Windows for me. Its very strange.

**Comment by sttng** [comment]
OK I think I found the issue. I think your Lego Digital Designer has a problem. Steps to solve:

1) Uninstall Lego Digital Designer
2) **Delete** this folder also (otherwise a reinstall will not work): 
C:\Users\Ilari\AppData\Roaming\LEGO Company\LEGO Digital Designer

3) Get this fixed version of LDD https://drive.google.com/file/d/1sEKCONjK2GtlbtUHauqpRTy3B1uUc3NO/view?usp=sharing

**Comment by ghost** [comment]
hah, thank you, it worked!
The models I tested worked, although that red rig didn't, for some reason :)

**Comment by sttng** [comment]
Cool, nice to hear. Maybe you can share some of your renders - assume you use Houdini. I'm still trying to improve my materials in RenderMan, but I am using a text editor to write shader networks (which is tedious).

**Comment by ghost** [comment]
Hi, yes, I'm in Houdini. I like Renderman, especially paired with USD. I would like to have it as my primary renderer. But on my laptop, I want to use GPU advantage and decided to give Arnold a try, still very new to Arnold.

I didn't find how to properly render it out to the disk with the new Houdini "Solaris" render manager, I hope it's not a bug. But just a noisy screenshot for now)
![image](https://user-images.githubusercontent.com/31226325/95290108-5781cf00-0821-11eb-9ad9-fef2908b97a9.png)

**Comment by sttng** [comment]
Nice. Sadly I couldn't get Houdini working for me on macOS.
