### ISSUE TITLE
AttributeError: 'Converter' object has no attribute 'scene'

### ISSUE THREAD

**Issue by Sarah-C** [sttng/LDD#7]
Hi!

I tried this: python pyldd2obj.py tie.lfx out.obj

And got this output:

C:\tmp>python pyldd2obj.py tie.lfx out.obj
- - - pyldd2obj - - -
          _
         [_]
       /|   |\
      ()'---' C
        | | |
        [=|=]

- - - - - - - - - - - -
Database FAIL
Traceback (most recent call last):
  File "C:\tmp\pyldd2obj.py", line 719, in <module>
    main()
  File "C:\tmp\pyldd2obj.py", line 714, in main
    converter.Export(filename=obj_filename)
  File "C:\tmp\pyldd2obj.py", line 590, in Export
    total = len(self.scene.Bricks)
AttributeError: 'Converter' object has no attribute 'scene'

C:\tmp>pause
Press any key to continue . . .

Could you be able to help me with it please?

**Comment by Sarah-C** [comment]
Ah, I copied the db across!

**Comment by sttng** [comment]
Try this one: https://github.com/sttng/LegoToR Stuff in this repo is just super old.

**Comment by sttng** [comment]
Closed :)
